config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  get '/dibs-referral', to: 'orders#populate'

  namespace :admin do
    resources :dibs_referrals
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  belongs_to :dibs_referral, class_name: 'Spree::User'
  scope :dibs_referrals, -> { where.not({ dibs_referral_id: nil, completed_at: nil }) }

  def dibs_referral_line_items
    result = {}
    result[:products] = {}
    result[:quantity] = {}
    result[:line_item_options] = {}
    line_items.each_with_index do |item, index|
      result[:products][index] = item.variant.id
      result[:quantity][item.variant.id] = item.quantity
      options = {}
      if item.respond_to?(:ad_hoc_option_values) and item.ad_hoc_option_values and !item.ad_hoc_option_values.empty?
        item.ad_hoc_option_values.each do | option |
          options[option.ad_hoc_option_type.id] = option.id
        end
      end
      result[:line_item_options][index] = options
    end
    result
  end

  def dibs_add_variant(item, ad_hoc_option_values)
    item.ad_hoc_option_values = ad_hoc_option_values.map { |cid| Spree::AdHocOptionValue.find(cid) }
    item.price = item.variant.price + item.ad_hoc_option_values.map(&:price_modifier).compact.sum
    item.save
  end

  def contains?(variant, ad_hoc_option_value_ids, product_customizations)
    nil
  end
end

app/models/spree/user_decorator.rb
Spree::User.class_eval do
  scope :dibs_referrers, lambda { includes(:spree_roles).where("#{::Spree::Role.table_name}.name" => "dibs_referral") }
  has_many :dibs_referrals, -> { uniq }, class_name: '::Spree::Order', foreign_key: 'dibs_referral_id'
end

app/models/user_decorator.rb
Spree.user_class.class_eval do
  scope :dibs_referrers, lambda { includes(:spree_roles).where("#{::Spree::Role.table_name}.name" => "dibs_referral") }
  has_many :dibs_referrals, class_name: '::Spree::Order', foreign_key: 'dibs_referral_id', uniq: true
end

app/controllers/application_decorator.rb
ApplicationController.class_eval do
  before_filter :dibs_session_referral, only: [:show, :edit, :index, :populate]

  private
    def dibs_session_referral
      if params[:dibs_referral]
        session[:dibs_referral] = URI::decode_www_form_component params[:dibs_referral] # See http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/29373
      end
    end
end

app/controllers/spree/admin/dibs_referrals_controller.rb
module Spree
  module Admin
    class DibsReferralsController < Admin::BaseController
      def index
        params[:q] ||= {}
        params[:q][:completed_at_not_null] ||= '1' if Spree::Config[:show_only_complete_orders_by_default]
        @show_only_completed = params[:q][:completed_at_not_null] == '1'
        params[:q][:s] = 'completed_at desc'
        params[:q][:dibs_referral_email_not_null] ||= '1'

        # As date params are deleted if @show_only_completed, store
        # the original date so we can restore them into the params
        # after the search
        created_at_gt = params[:q][:created_at_gt]
        created_at_lt = params[:q][:created_at_lt]

        params[:q].delete(:inventory_units_shipment_id_null) if params[:q][:inventory_units_shipment_id_null] == "0"

        if !params[:q][:created_at_gt].blank?
          params[:q][:created_at_gt] = Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day rescue ""
        end

        if !params[:q][:created_at_lt].blank?
          params[:q][:created_at_lt] = Time.zone.parse(params[:q][:created_at_lt]).end_of_day rescue ""
        end

        params[:q][:completed_at_gt] = params[:q].delete(:created_at_gt)
        params[:q][:completed_at_lt] = params[:q].delete(:created_at_lt)

        @search = Order.accessible_by(current_ability, :index).ransack(params[:q])

        # lazyoading other models here (via includes) may result in an invalid query
        # e.g. SELECT  DISTINCT DISTINCT "spree_orders".id, "spree_orders"."created_at" AS alias_0 FROM "spree_orders"
        # see https://github.com/spree/spree/pull/3919
        @referrals = @search.result(distinct: true).
          page(params[:page]).
          per(params[:per_page] || Spree::Config[:orders_per_page])

        # Restore dates
        params[:q][:created_at_gt] = created_at_gt
        params[:q][:created_at_lt] = created_at_lt
      end
    end
  end
end

app/controllers/spree/checkout_controller_decorator.rb
Spree::CheckoutController.class_eval do
  after_filter :dibs_capture_referral, only: :edit

  def dibs_capture_referral
    if session[:dibs_referral] and (!@current_order.dibs_referral or session[:dibs_referral] != @current_order.dibs_referral.email)
      @current_order.dibs_referral = Spree.user_class.find_by_email(session[:dibs_referral])
      @current_order.save
    end
  end

end

app/controllers/spree/orders_controller_decorator.rb
Spree::OrdersController.class_eval do
  before_filter :dibs_before, only: :populate
  after_filter :dibs_after, only: :populate

  def dibs_before
    params.permit(:dibs_referral_id)
    return if !request.get?
    dibs_empty
  end

  def dibs_after
    return if !request.get?
    return if !params.include? :line_item_options
    @order = current_order
    @order.line_items.each_with_index do |item, index|
      params[:ad_hoc_option_values] = params[:line_item_options]["#{index}"]
      @order.dibs_add_variant(item, ad_hoc_option_value_ids)
    end
    @order.update!
  end

  def dibs_empty
      @current_order.line_items.destroy_all if @current_order
  end

end

app/helpers/dibs_referrals_helper.rb
module DibsReferralsHelper
end

app/views/spree/admin/dibs_referrals/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_filters) %>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div>
    <%= search_form_for [:admin, @search], url: admin_dibs_referrals_path do |f| %>
      <div class="field-block alpha four columns">
        <div class="date-range-filter field">
          <%= label_tag nil, Spree.t(:date_range) %>
          <div class="date-range-fields">
            <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from', :value => params[:q][:created_at_gt], :placeholder => Spree.t(:start) %>

            <span class="range-divider">
              <i class="icon-arrow-right"></i>
            </span>

            <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to', :value => params[:q][:created_at_lt], :placeholder => Spree.t(:stop) %>
          </div>
        </div>

      </div>

      <div class="four columns">
        <div class="field">
          <%= label_tag nil, Spree.t(:order_number, :number => '') %>
          <%= f.text_field :number_cont %>
        </div>
        <div class="field">
          <%= label_tag nil, Spree.t(:referral_email) %>
          <%= f.email_field :dibs_referral_email_cont %>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_orders_index_search_buttons">
          <%= button Spree.t(:filter_results), 'icon-search' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<%= paginate @referrals %>

<% unless @referrals.any? %>
<h2>No referrals</h2>
<% else %>
<table>
  <thead>
    <th>Completion Date</th>
    <th>Number</th>
    <th>Referral</th>
    <th>Total</th>
  </thead>
  <% @referrals.each do |referral| %>
  <tr>
    <td><%= referral.completed_at.to_date %></td>
    <td><%= referral.number %></td>
    <td><%= referral.dibs_referral.email %></td>
    <td><%= referral.display_total.to_html %></td>
  <tr>
  <% end %>
  </table>
<% end %>

<%= paginate @referrals %>